#!/bin/sh /etc/rc.common
# Copyright (C) 2011 OpenWrt.org

USE_PROCD=1
PROG=/usr/bin/wifi_monitor

start_service() {
    procd_open_instance
	procd_set_param command $PROG
	procd_set_param respawn
	procd_close_instance
}
