#!/bin/sh /etc/rc.common
# Copyright (C) 2011 OpenWrt.org

START=78
USE_PROCD=1
PROG=/usr/bin/property_service


start_service() {
    procd_open_instance
	procd_set_param command $PROG --system --daemonize=no
	procd_set_param respawn
	procd_close_instance
}
