#!/bin/sh /etc/rc.common
# Copyright (C) 2011 OpenWrt.org

START=87
USE_PROCD=1
PROG=/usr/bin/lumenflinger

start_service() {
    procd_open_instance
    procd_set_param command $PROG 3021
    procd_set_param respawn 3600 2 -1
    procd_set_param stdout 1
    procd_close_instance
}
