#!/bin/sh /etc/rc.common
# Copyright (C) 2011 OpenWrt.org

START=96
USE_PROCD=1
PROG=/bin/bash

start_service() {
    procd_open_instance
    procd_set_param command $PROG /usr/yoda/services/healthz/healthz
    procd_set_param respawn 3600 2 -1
    procd_set_param stdout 1
    procd_set_param stderr 1
    [ -e /data/coredump ] && {
        procd_set_param limits core="unlimited"
    }
    procd_close_instance
}
