#!/bin/sh /etc/rc.common
START=85

SERVICE_PID_FILE=/var/run/adbd.pid
#PROG=/usr/bin/adbd


usb_rndis_init()
{
    mount -t configfs none /sys/kernel/config
    mkdir /sys/kernel/config/usb_gadget/amlogic
    cd /sys/kernel/config/usb_gadget/amlogic
    echo 0x18D1 > idVendor
    echo 0x4e26 > idProduct
    mkdir strings/0x409
	CMD=`cat /proc/cmdline | grep androidboot.serialno`
	SERIAL_NO=`echo ${CMD#*"androidboot.serialno="} |awk '{print $1}'`

	if [ ! $SERIAL_NO ]; then
	      SERIAL_NO=0123456789ABCDEF
	else
	      echo ${SERIAL_NO}
	fi
    echo ${SERIAL_NO} > strings/0x409/serialnumber
    echo amlogic > strings/0x409/manufacturer
    echo p212 > strings/0x409/product
    mkdir configs/amlogic.1
    mkdir configs/amlogic.1/strings/0x409
    #echo rndis > configs/amlogic.1/strings/0x409/configuration
    echo 500 > configs/amlogic.1/MaxPower
    mkdir functions/rndis.rndis
    ln -s functions/rndis.rndis configs/amlogic.1
    cd /
}

usb_adbd_init()
{
    echo "adb" > /sys/kernel/config/usb_gadget/amlogic/configs/amlogic.1/strings/0x409/configuration
    mkdir /sys/kernel/config/usb_gadget/amlogic/functions/ffs.adb
    mkdir /dev/usb-ffs
    mkdir /dev/usb-ffs/adb
    mount -t functionfs adb /dev/usb-ffs/adb
    ln -s /sys/kernel/config/usb_gadget/amlogic/functions/ffs.adb /sys/kernel/config/usb_gadget/amlogic/configs/amlogic.1/ffs.adb
    /usr/bin/adbd &
}

start () {
	#usb_dir=/sys/kernel/config/usb_gadget/amlogic
	#if [ ! -d ${usb_dir} ]
	#then
	#{
		usb_rndis_init
		usb_adbd_init
		sleep 5
		echo ff500000.dwc2_a > /sys/kernel/config/usb_gadget/amlogic/UDC
	#}&
	#fi
}
stop () {
	killall adbd
}
