#!/bin/ash

echo 0 > /sys/class/rfkill/rfkill0/state

echo "load hci_uart.ko"
MODULE_PATH=/lib/modules/`uname -r`
insmod ${MODULE_PATH}/hci_uart.ko

usleep 200000

echo 1 > /sys/class/rfkill/rfkill0/state
usleep 500000

mkdir -p /data/bluetooth/
echo "load 8723 bs or ds bluetooth firmware"
/usr/sbin/rtk_hciattach -n -s 115200 ttyS4 rtk_h5 &
echo "Waiting bluetooth init......"

retry_count=0
while [ ! -x "/sys/class/bluetooth/hci0" ]
do
    sleep 1
    retry_count=$(($retry_count+1))
    if [ $retry_count -ge 3 ]
    then
        echo "bluetooth init greater than 3 seconds."
        #killall -9 rtk_hciattach
        exit
    fi
done
echo "bluetooth init successful"
# load the firmware need time, the the worst time is 2.6 s.
