#!/bin/sh

NAME=lumenflinger
DAEMON=/usr/bin/$NAME
PIDFILE=/var/run/$NAME.pid
REPLYPIDFILE=/var/run/lumenflinger.pid

case "$1" in
	start)
		echo "Starting lumenflinger..."
		start-stop-daemon -S -m -p $PIDFILE -b -x $DAEMON 
		;;
	stop)
		echo -n "Stopping lumenflinger..."
		start-stop-daemon -K -o -p $PIDFILE
		rm -f $PIDFILE
		;;
	restart|reload)
		echo "Restarting lumenflinger..."
		start-stop-daemon -K -o -p $PIDFILE
		start-stop-daemon -S -m -p $PIDFILE -b -x $DAEMON 
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?

