#!/bin/sh /etc/rc.common
# Copyright (C) 2011 OpenWrt.org

START=81
USE_PROCD=1
PROG=/usr/bin/flora-dispatcher

start_service() {
    procd_open_instance
    procd_set_param command  $PROG --uri=unix:/var/run/flora.sock --uri=tcp://0.0.0.0:37800/ --msg-buf-size=81920 --log-service-port=37701
    procd_set_param respawn 3600 2 -1
    procd_set_param stdout 1
    [ -e /data/coredump ] && {
        procd_set_param limits core="unlimited"
    }
    procd_close_instance
}
