#!/bin/sh /etc/rc.common
# Copyright (C) 2011 OpenWrt.org

START=82
USE_PROCD=1
PROG=/usr/bin/net_manager

start_service() {
    procd_open_instance
    procd_set_param command $PROG
    procd_set_param respawn
    [ -e /data/coredump ] && {
        procd_set_param limits core="unlimited"
    }
    procd_close_instance
}
