set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR armv7l)

set(CMAKE_SYSROOT ${CMAKE_EXTERNAL_SYSROOT})
set(CMAKE_C_COMPILER ${CMAKE_TOOLCHAIN_ROOT}/arm-openwrt-linux-gnueabi-gcc)
set(CMAKE_C_COMPILER_WORKS TRUE)
