set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR armv8l)

set(CMAKE_SYSROOT ${CMAKE_EXTERNAL_SYSROOT})
set(CMAKE_C_COMPILER ${CMAKE_TOOLCHAIN_ROOT}/armv8l-linux-gnueabihf-gcc)
set(CMAKE_C_COMPILER_WORKS TRUE)
message("TOOLCHAIN C COMPILER sweet: ${CMAKE_TOOLCHAIN_ROOT}/armv8l-linux-gnueabihf-gcc")
