#!/bin/sh /etc/rc.common
# Copyright (C) 2011 OpenWrt.org

START=93
USE_PROCD=1
PROG="nice -n -11 /bin/startup -t 20 -f /tmp/.com.rokid.activation.bootts /usr/bin/turenproc 30000 kamino_mini unix:/var/run/flora.sock"

start_service() {
    procd_open_instance
    procd_set_param command  $PROG
    procd_set_param respawn 3600 2 -1
    procd_set_param env LD_LIBRARY_PATH=/usr:/usr/lib:/usr/lib/hw
    #procd_set_param stdout 1
    #procd_set_param stderr 1
    [ -e /data/coredump ] && {
        procd_set_param limits core="unlimited"
    }
    procd_close_instance
}
