#!/bin/sh /etc/rc.common
# Copyright (C) 2011 OpenWrt.org

START=89
USE_PROCD=1
PROG=/usr/bin/bluetooth_service

start_service() {
    mkdir -p /var/run/bluetooth

    procd_open_instance
    procd_set_param command $PROG
    procd_set_param respawn 3600 2 -1
    procd_set_param stdout 1
    procd_set_param stderr 1
    # procd_set_param limits core="unlimited"
    procd_close_instance
}
