#!/bin/sh /etc/rc.common
# Copyright (C) 2011 OpenWrt.org

START=94
USE_PROCD=1
PROG="/bin/startup -t 30 -f /tmp/.com.rokid.activation.bootts /usr/bin/homebase.sh"


start_service() {
    procd_open_instance
    procd_set_param command $PROG
    procd_set_param respawn 3600 2 -1
    procd_set_param stdout 1
    [ -e /data/coredump ] && {
        procd_set_param limits core="unlimited"
    }
    procd_close_instance
}
