#!/bin/sh /etc/rc.common
# Copyright (C) 2011 OpenWrt.org

START=86
USE_PROCD=1
PROG=/usr/bin/log2cloud

start_service() {
    procd_open_instance
    procd_set_param command $PROG
    procd_set_param respawn 3600 2 -1
    procd_close_instance
}